src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GamesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GamesRepository::class)]
class Games
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_games = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $player_games = null;

    #[ORM\Column]
    private ?int $score_games = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateGames(): ?\DateTimeInterface
    {
        return $this->date_games;
    }

    public function setDateGames(\DateTimeInterface $date_games): self
    {
        $this->date_games = $date_games;

        return $this;
    }

    public function getPlayerGames(): ?Users
    {
        return $this->player_games;
    }

    public function setPlayerGames(?Users $player_games): self
    {
        $this->player_games = $player_games;

        return $this;
    }

    public function getScoreGames(): ?int
    {
        return $this->score_games;
    }

    public function setScoreGames(int $score_games): self
    {
        $this->score_games = $score_games;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\GamesRepository;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(GamesRepository $gamesRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'games' => $gamesRepository->findBy(array(),array('score_games' => 'DESC'))
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/home.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
<style>
</style>

<div class="container">
    <h1 id="homeTitle">SCOREBOARD</h1>
    <div class="DivRankOfTheMoment">
        <div class="RankOfTheMoment">
            <h2 class="titleRank">Rank of the day</h2>
            <table>
                <tr>
                    <td></td>
                    <td>Player</td>
                    <td>Score</td>
                    <td>Rank</td>
                    {% set i = 0 %}
                    {% for game in games %}
                        {% set i = i+1 %}
                        {% if (i<11) %}
                            <tr class="rowRank">
                                <td></td>
                                <td>{{ game.playerGames.UsernameUsers}}</td>
                                <td>{{ game.scoreGames}}</td>
                                {% if (i<4) %}
                                    <td><img class="imgMedalsMoment" src="../img/medal{{i}}.png" alt="imgMedals"></td>
                                {% else %}
                                    <td>#{{i}}</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>
        </div>
        <div class="RankOfTheMoment">
            <h2 class="titleRank">Rank of the week</h2>
            <table>
                <tr>
                    <td></td>
                    <td>Player</td>
                    <td>Score</td>
                    <td>Rank</td>
                    {% set i = 0 %}
                    {% for game in games %}
                        {% set i = i+1 %}
                        {% if (i<11) %}
                            <tr class="rowRank">
                                <td></td>
                                <td>{{ game.playerGames.UsernameUsers}}</td>
                                <td>{{ game.scoreGames}}</td>
                                {% if (i<4) %}
                                    <td><img class="imgMedalsMoment" src="../img/medal{{i}}.png" alt="imgMedals"></td>
                                {% else %}
                                    <td>#{{i}}</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>
        </div>
        <div class="RankOfTheMoment">
            <h2 class="titleRank">Rank of the month</h2>
            <table>
                <tr class="rowRank">
                    <td></td>
                    <td>Player</td>
                    <td>Score</td>
                    <td>Rank</td>
                    {% set i = 0 %}
                    {% for game in games %}
                        {% set i = i+1 %}
                        {% if (i<11) %}
                            <tr class="rowRank">
                                <td></td>
                                <td>{{ game.playerGames.UsernameUsers}}</td>
                                <td>{{ game.scoreGames}}</td>
                                {% if (i<4) %}
                                    <td><img class="imgMedalsMoment" src="../img/medal{{i}}.png" alt="imgMedals"></td>
                                {% else %}
                                    <td>#{{i}}</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>

    <div class="CTA">
        <button class="buttonPlay"><a href="{{ path('app_play') }}">Let's Try !</a></button>
    </div>
    <div class="DivRankOfAllTime">
        <div class="RankOfAllTime">
            <h2 class="titleRank">Rank of all time</h2>
            <table>
                <tr>
                    <td></td>
                    <td>Player</td>
                    <td>Score</td>
                    <td>Rank</td>
                    {% set i = 0 %}
                    {% for game in games %}
                        {% set i = i+1 %}
                        {% if (i<11) %}
                            <tr class="rowRank">
                                <td></td>
                                <td>{{ game.playerGames.UsernameUsers}}</td>
                                <td>{{ game.scoreGames}}</td>
                                {% if (i<4) %}
                                    <td><img class="imgMedalsAllTime" src="../img/medal{{i}}.png" alt="imgMedals"></td>
                                {% else %}
                                    <td>#{{i}}</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>
{% endblock %}