src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GamesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GamesRepository::class)]
class Games
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_games = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $player_games = null;

    #[ORM\Column]
    private ?int $score_games = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateGames(): ?\DateTimeInterface
    {
        return $this->date_games;
    }

    public function setDateGames(\DateTimeInterface $date_games): self
    {
        $this->date_games = $date_games;

        return $this;
    }

    public function getPlayerGames(): ?Users
    {
        return $this->player_games;
    }

    public function setPlayerGames(?Users $player_games): self
    {
        $this->player_games = $player_games;

        return $this;
    }

    public function getScoreGames(): ?int
    {
        return $this->score_games;
    }

    public function setScoreGames(int $score_games): self
    {
        $this->score_games = $score_games;

        return $this;
    }
}

src/Form/GamesType.php
<?php

namespace App\Form;

use App\Entity\Games;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GamesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_games')
            ->add('player_games')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Games::class,
        ]);
    }
}

src/Controller/GamesController.php
<?php

namespace App\Controller;

use App\Entity\Games;
use App\Form\GamesType;
use App\Repository\GamesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/games')]
class GamesController extends AbstractController
{
    #[Route('/', name: 'app_games_index', methods: ['GET'])]
    public function index(GamesRepository $gamesRepository): Response
    {
        return $this->render('games/index.html.twig', [
            'games' => $gamesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_games_new', methods: ['GET', 'POST'])]
    public function new(Request $request, GamesRepository $gamesRepository): Response
    {
        $game = new Games();
        $form = $this->createForm(GamesType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $gamesRepository->save($game, true);

            return $this->redirectToRoute('app_games_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('games/new.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_games_show', methods: ['GET'])]
    public function show(Games $game): Response
    {
        return $this->render('games/show.html.twig', [
            'game' => $game,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_games_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Games $game, GamesRepository $gamesRepository): Response
    {
        $form = $this->createForm(GamesType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $gamesRepository->save($game, true);

            return $this->redirectToRoute('app_games_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('games/edit.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_games_delete', methods: ['POST'])]
    public function delete(Request $request, Games $game, GamesRepository $gamesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$game->getId(), $request->request->get('_token'))) {
            $gamesRepository->remove($game, true);
        }

        return $this->redirectToRoute('app_games_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/games/_delete_form.html.twig
<form method="post" action="{{ path('app_games_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/games/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/games/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Games{% endblock %}

{% block body %}
    <h1>Edit Games</h1>

    {{ include('games/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_games_index') }}">back to list</a>

    {{ include('games/_delete_form.html.twig') }}
{% endblock %}

templates/games/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games index{% endblock %}

{% block body %}
    <h1>Games index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_games</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td>{{ game.id }}</td>
                <td>{{ game.dateGames ? game.dateGames|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_games_show', {'id': game.id}) }}">show</a>
                    <a href="{{ path('app_games_edit', {'id': game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_games_new') }}">Create new</a> #}
{% endblock %}

templates/games/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Games{% endblock %}

{% block body %}
    <h1>Create new Games</h1>

    {{ include('games/_form.html.twig') }}

    <a href="{{ path('app_games_index') }}">back to list</a>
{% endblock %}

templates/games/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games{% endblock %}

{% block body %}
    <h1>Games</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ game.id }}</td>
            </tr>
            <tr>
                <th>Date_games</th>
                <td>{{ game.dateGames ? game.dateGames|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_games_index') }}">back to list</a>

    <a href="{{ path('app_games_edit', {'id': game.id}) }}">edit</a>

    {{ include('games/_delete_form.html.twig') }}
{% endblock %}